# This is a basic workflow to help you get started with Actions
name: Windows Paths
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# name: Windows paths

# on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "pypy-3.7"
          - "pypy-3.8"
        architecture: ["x86", "x64"]

    steps:
      - name: Build on Windows
        if: runner.os == 'Windows'
        run: |
          choco install libsndfile
          New-Item -ItemType Junction -Path "C:\libsndfile" -Target "C:\Program Files\libsndfile"
          Set-Item -Path Env:LIB -Value "-LC:\libsndfile\bin"
          Set-Item -Path Env:INCLUDE -Value "-IC:\libsndfile\include"
          $Env:windir
          refreshenv
          vswhere.exe -latest -property installationPath
          Get-ChildItem C:\libsndfile\lib
          Get-ChildItem C:\libsndfile\bin
          Get-ChildItem C:\libsndfile\include
